# Generated by Django 5.0.4 on 2024-06-19 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('School', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='School.branch'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='parents', to='School.school'),
        ),
        migrations.AlterField(
            model_name='student',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='School.school'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='School.branch'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='School.school'),
        ),
    ]
