# Generated by Django 5.0.4 on 2024-06-22 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('School', '0002_alter_parent_branch_alter_parent_school_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_no', models.CharField(max_length=3)),
                ('section', models.CharField(max_length=1)),
                ('class_student', models.ManyToManyField(to='School.student')),
                ('class_teacher', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='School.teacher')),
            ],
        ),
    ]
