# Generated by Django 5.0.4 on 2024-06-22 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('School', '0003_classes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='name',
        ),
    ]
